/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-11-20 22:07:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorLandingPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t<title>Doctor Landing Page</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/datatables.css\">\r\n");
      out.write("\t\t \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write(" \t<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\"> \r\n");
      out.write("    <link href=\"css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("   <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script> \r\n");
      out.write("       <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">   \r\n");
      out.write("   <script src=\"js/opentip-jquery.js\"></script><!-- Change to the adapter you actually use -->\r\n");
      out.write("\t<link href=\"css/opentip.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">   \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write(" \t $(function() {\t  \r\n");
      out.write("\t\t$(\"#refreshLink\").click( function() {\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.location.href=\"userDetailsForDoctor\";  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*$.ajax({\r\n");
      out.write("\t\t\t\t type: \"POST\",\t\t\t \r\n");
      out.write("\t  \t         url: \"userDetailsForDoctor\",\r\n");
      out.write("\t  \t      \t data: null,\r\n");
      out.write("\t  \t         \r\n");
      out.write("\t  \t         success: function(data) {    \t    \t        \t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  var tr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     for (var i = 0; i < data.length; i++) {\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t /* alert(data[i].lastName); */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t          /*   tr = $('<tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            tr.append('<td><input type=\"radio\" name=\"optionRadios\" value=\"\"></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            tr.append('<td id='+data[i].BID+'>' + data[i].firstName + '</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            tr.append('<td>' + data[i].lastName + '</td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            tr.append('<td class=\"center\">' + data[i].gender + '</td></tr>'); */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t           /*  var row = '<tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            row += '<td><input type=\"radio\" name=\"optionRadios\" value=\"\"></td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                row += '<td id='+ data[i].BID + '>' + data[i].firstName+ '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                row += '<td>' + data[i].lastName + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                row += '<td>' + data[i].gender + '</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \r\n");
      out.write("\t\t\t\t\t\t\t\t\t             \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                row += '</tr>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                $(\"table tbody\").append(row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t  \t         \r\n");
      out.write("\t  \t         }\r\n");
      out.write("\t        });*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t\r\n");
      out.write("\t }); \r\n");
      out.write("\r\n");
      out.write(" \t /* ToolTip */\r\n");
      out.write(" \t Opentip.styles.selectPatient = {\t\t\t  \r\n");
      out.write("\t\t\t   extends: \"alert\",\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  target: true, \t\t\t\r\n");
      out.write("\t\t\t  showEffectDuration: 0.5,\r\n");
      out.write("\t\t\t  hideEffectDuration:0.3,\r\n");
      out.write("\t \t\t  stem: true, \r\n");
      out.write("\t \r\n");
      out.write("\t \t\t offset: [-380,-12], \r\n");
      out.write("\t \t \t hideTrigger: \"trigger\", \r\n");
      out.write("\t\t\t  hideTriggers:[\"closeButton\",\"trigger\", \"tip\", \"target\", \"closeButton\"],\r\n");
      out.write("\r\n");
      out.write("\t\t\t  closeButtonRadius: 7,\r\n");
      out.write("\t\t\t  closeButtonCrossSize: 7,\r\n");
      out.write("\t\t\t  closeButtonCrossColor:\"#FFFFFF\",\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  showOn: \"creation\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    var buttonID;\r\n");
      out.write("\t$(function() {\t  \r\n");
      out.write("\t\t$(\"#createBodyMap\").click( function() {\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tbuttonID = $(this).attr(\"id\");\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t     var checked = $(\"input[name=optionRadios]:checked\");\t\r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     if(checked.val()!=null)\r\n");
      out.write("\t\t\t    \t {\r\n");
      out.write("\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t    \tvar id=$(checked).closest('tr').children('td:eq(1)').attr('id');\t\t\t\r\n");
      out.write("\t\t\t    \tdocument.location.href=\"SetFlagServlet?Id=\"+id;\t\t     \r\n");
      out.write("\t\t\t\t    \t \r\n");
      out.write("\t\t\t    \t }\r\n");
      out.write("\t\t\t     else\r\n");
      out.write("\t\t\t    \t {\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tnew Opentip(\"#reference\", \"Select a Patient!\", {  style: \"selectPatient\" });\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    \t }\r\n");
      out.write("\t \r\n");
      out.write("\t\t });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\t  \r\n");
      out.write("\t\t$(\"#deletePatient\").click( function() {\t\t\t\t\t\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t var checked = $(\"input[name=optionRadios]:checked\");\t\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t     if(checked.val()!=null)\r\n");
      out.write("\t\t    \t {\r\n");
      out.write("\t\t\t\t\t    \t\r\n");
      out.write("\t\t    \tvar id=$(checked).closest('tr').children('td:eq(1)').attr('id');\r\n");
      out.write("\t\t    \tdocument.location.href=\"DeletePatient?Id=\"+id;\t\t     \r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t    \t }\r\n");
      out.write("\t\t     else\r\n");
      out.write("\t\t    \t {\r\n");
      out.write("\t\t    \t \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \t\tnew Opentip(\"#reference\", \"Select a Patient!\", {  style: \"selectPatient\" });\r\n");
      out.write("\t\t    \t \r\n");
      out.write("\t\t    \t }\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderLayout.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("        \r\n");
      out.write("\t  <div class=\"container\" style=\"height: 100%\">\r\n");
      out.write("        <div class=\"row\" style=\"overflow: auto;\"> \r\n");
      out.write("        <div class=\"box\" style=\"height: auto;\">    \r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "DoctorMenuLayout.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-3\" style=\"margin-top:0; right: 1%\">\r\n");
      out.write("            <div class=\"panel panel-primary\" style=\"width: 100%; height: 520px;\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\" style=\"text-align: center\"><i class=\"fa fa-user\"></i> Doctor Info</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"list-group\">                  \r\n");
      out.write("                  <a class=\"list-group-item\">                    \r\n");
      out.write("                    <i class=\"fa fa-user\"></i> <label> First Name:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a class=\"list-group-item\">                 \r\n");
      out.write("                    <i class=\"fa fa-user\"></i>  <label>Last Name:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a class=\"list-group-item\">                 \r\n");
      out.write("                    <i class=\"fa fa-check\"></i>  <label>Age:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                   <a class=\"list-group-item\">                 \r\n");
      out.write("                    <i class=\"fa fa-male\"></i> <label> Gender: </label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                   <a class=\"list-group-item\">                 \r\n");
      out.write("                    <i class=\"fa fa-envelope\"> </i> <label> Email:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                   <a class=\"list-group-item\">                 \r\n");
      out.write("                    <i class=\"fa fa-tag\"></i>  <label>Doctor ID:</label> ");
      out.write("\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View full profile <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"col-lg-9\" style=\"margin-top:0;\">\r\n");
      out.write("            <h2>Body Map <small>Doctor Dashboard</small></h2>\r\n");
      out.write("            <ol class=\"breadcrumb\" style=\"width: 82%\">\r\n");
      out.write("              <li class=\"active\"><i class=\"fa fa-dashboard\"></i> Dashboard</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("      <form action=\"\">\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-8\">\r\n");
      out.write("            <h4>Registered Patients <small>(without bodymap) <a href=\"#\" id=\"refreshLink\" > <i class=\"fa fa-refresh\" style=\"color: black\"></i></a> </small></h4>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"datatable table table-striped table-bordered\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><i class=\"fa fa-check\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>First Name <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Last Name <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Gender</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><i class=\"fa fa-check\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>First Name <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Last Name <i class=\"fa fa-sort\"></i></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Gender</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-4\" style=\"margin-top: 13.5%;\">\r\n");
      out.write("\t\t           <p>              \r\n");
      out.write("\t\t          <button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"createBodyMap\">Create Body Map</button>\r\n");
      out.write("\t\t          </p>\r\n");
      out.write("\t          \r\n");
      out.write("\t\t           <p>              \r\n");
      out.write("\t\t          <button type=\"button\" class=\"btn btn-primary btn-lg\" id=\"deletePatient\">Delete Patient</button>\r\n");
      out.write("\t\t          </p>\r\n");
      out.write("           \r\n");
      out.write("\t\t    </div> \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterLayout.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<script src=\"//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/datatables.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('.datatable').dataTable({\r\n");
      out.write("\t\t\t\t\"sPaginationType\": \"bs_normal\"\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t$('.datatable').each(function(){\r\n");
      out.write("\t\t\t\tvar datatable = $(this);\r\n");
      out.write("\t\t\t\t// SEARCH - Add the placeholder for Search and Turn this into in-line form control\r\n");
      out.write("\t\t\t\tvar search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');\r\n");
      out.write("\t\t\t\tsearch_input.attr('placeholder', 'Search');\r\n");
      out.write("\t\t\t\tsearch_input.addClass('form-control input-sm');\r\n");
      out.write("\t\t\t\t// LENGTH - Inline-Form control\r\n");
      out.write("\t\t\t\tvar length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');\r\n");
      out.write("\t\t\t\tlength_sel.addClass('form-control input-sm');\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tOpentip.styles.refreshTip = {\t\t\t  \r\n");
      out.write("\t\t\t\t\t   extends: \"dark\",\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  target: true, \t\t\t\r\n");
      out.write("\t\t\t\t\t  showEffectDuration: 0.5,\r\n");
      out.write("\t\t\t\t\t  hideEffectDuration:0.3,\r\n");
      out.write("\t\t\t \t\t  stem: true, \r\n");
      out.write("\t\t\t \t \t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \t \t hideTrigger: \"trigger\", \r\n");
      out.write("\t\t\t\t\t  hideTriggers:[\"closeButton\",\"trigger\", \"tip\", \"target\", \"closeButton\"],\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  closeButtonRadius: 7,\r\n");
      out.write("\t\t\t\t\t  closeButtonCrossSize: 7,\r\n");
      out.write("\t\t\t\t\t  closeButtonCrossColor:\"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  showOn: \"creation\"\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tnew Opentip(\"#refreshLink\", \"Refresh your Patient List\", {  style: \"refreshTip\" });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /DoctorLandingPage.jsp(240,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registration ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /DoctorLandingPage.jsp(242,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /DoctorLandingPage.jsp(242,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(registration)-1}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).intValue());
    // /DoctorLandingPage.jsp(242,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("index");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t <tr>\r\n");
          out.write("                    \t<td><input type=\"radio\" name=\"optionRadios\" value=\"\"></td>\r\n");
          out.write("                  \t\t<td id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registration[index].getBID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"checkBox\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registration[index].getFirstName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\r\n");
          out.write("                  \t\t<td id=\"reference\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registration[index].getLastName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td> \r\n");
          out.write("                    \t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registration[index].getGender()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\r\n");
          out.write("\t\t\t\t\t </tr>\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
