/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-11-20 10:00:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorPrintReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write(" \t<link rel=\"icon\" type=\"image/png\" href=\"img/icon.PNG\">\r\n");
      out.write("    <title>Patient Home</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("   <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\"> \r\n");
      out.write("    <link href=\"css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("     <script src=\"js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">   \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://cdn.oesmith.co.uk/morris-0.4.3.min.css\">   \r\n");
      out.write("    <script src=\"js/Three.js\"></script>\r\n");
      out.write("    <script src=\"js/OBJLoader.js\"></script>\r\n");
      out.write("   <script src=\"http://d3js.org/d3.v3.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"js/d3.v3.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("    #obj{\r\n");
      out.write("    \r\n");
      out.write("    display: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    $( document ).ready(function() {\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("   \t var $ = jQuery.noConflict();\r\n");
      out.write("   \t  var patientGender = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("   \t \r\n");
      out.write("   \t  \r\n");
      out.write("   \t  \r\n");
      out.write("   \t  \r\n");
      out.write("   \t  \r\n");
      out.write("   \tif(patientGender==\"M\")\r\n");
      out.write("   \t\t{\r\n");
      out.write("   \t\t\t\r\n");
      out.write("   \t\t   $.getScript(\"js/Male.js\");\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\r\n");
      out.write("   \telse if (patientGender==\"F\")\r\n");
      out.write("   \t\t{\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t $.getScript(\"js/Female.js\");\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t$(\"#generateReportForDoc\").click( function(){\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\tvar page=\"DPR\";\r\n");
      out.write("   \t\tvar bid = document.getElementById(\"bodyIDPrintInput\").value;\r\n");
      out.write("     \t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\tdocument.location.href=\"GetAllAnnotationsAction?bid=\"+bid+\"&page=\"+page;\t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t});\r\n");
      out.write("    \r\n");
      out.write("   \t\r\n");
      out.write("   \t$('#switch').click(function() {\r\n");
      out.write("   \t\t\r\n");
      out.write("        $('#pageone').hide();\r\n");
      out.write("        $('#obj').show();\r\n");
      out.write("    /*  }, function() {\r\n");
      out.write("        $('#obj').hide();\r\n");
      out.write("        $('#pageone').show();  */\r\n");
      out.write("});\r\n");
      out.write("   \t\r\n");
      out.write("   \t$('#leftarrow').click(function() {\r\n");
      out.write("   \t\t\r\n");
      out.write("        $('#obj').hide();\r\n");
      out.write("        $('#pageone').show();\r\n");
      out.write("    /*  }, function() {\r\n");
      out.write("        $('#obj').hide();\r\n");
      out.write("        $('#pageone').show();  */\r\n");
      out.write("});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderLayout.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("       <div class=\"container\">\r\n");
      out.write("      <div class=\"row\" style=\"overflow: auto;\"> \r\n");
      out.write("        <div class=\"box\" style=\"height: auto;\">      \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write(" <!--         <div id=\"wrapper\">  -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "DoctorMenuLayout.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <div id=\"page-wrapper\">\r\n");
      out.write(" \r\n");
      out.write(" <!--Col1  -->\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("  \t<div class=\"col-lg-5\" style=\"top:-20px;left:2px;\">\r\n");
      out.write("            <h2>Body Map <small>Print Report</small></h2>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("              <li class=\"active\"><i class=\"fa fa-eye\"></i> Print Report</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            \r\n");
      out.write("         <!--  <h4 id=\"patientName\" align=\"center\"></h4> -->\r\n");
      out.write("            <!-- <div class=\"alert alert-success alert-dismissable\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("             This is the Body Map View Mode!!   </div> -->\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             <form role=\"form\" id=\"myForm\">\r\n");
      out.write("     <div class=\"form-group\">\r\n");
      out.write("                <label>Body Map ID</label>\r\n");
      out.write("                <input class=\"form-control\" id=\"bodyIDPrintInput\" placeholder=\"Enter Body Map ID\" required=\"required\" autocomplete=\"on\" autofocus=\"autofocus\">\r\n");
      out.write("     </div>\r\n");
      out.write("       <div class=\"btn-group\">\r\n");
      out.write("        <button type=\"button\" id=\"generateReportForDoc\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"caret\"></span></button>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li style=\"height: 30px;\"><a href=\"#\" id=\"female\" title=\"not implemented\">Convert to PDF</a></li>   \r\n");
      out.write("                   <li style=\"height: 30px;\"><a href=\"#\" id=\"female\" title=\"not implemented\">Print Report</a></li>   \r\n");
      out.write("                                          \r\n");
      out.write("                  </ul>\r\n");
      out.write("             </div>     \r\n");
      out.write("                  \r\n");
      out.write("</form>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("<!--  style=\"height: 30px;\" -->\r\n");
      out.write("            \r\n");
      out.write("  <!--Col1 Ends -->\r\n");
      out.write("\r\n");
      out.write("\t <!--Col2 -->\r\n");
      out.write("\t<a href=\"#\" id=\"leftarrow\" style=\"position: absolute; top: 40%; right:58%\"> <i class=\"fa fa-chevron-left\" id=\"leftarrow\"></i></a>\r\n");
      out.write("\t  <form role=\"form\" id=\"reportForm\">\r\n");
      out.write("\t  <div class=\"col-lg-6\" style=\"border:1px solid;top:-10px\">\r\n");
      out.write("\t<h3 align=\"center\">2D Body Map for EHR</h3>\r\n");
      out.write("\t<h4 align=\"center\">Report</h4>\r\n");
      out.write("\t<hr>\r\n");
      out.write("<div id=\"pageone\">\r\n");
      out.write("  <div class=\"row\" > \r\n");
      out.write("  <div class=\"col-lg-5\">\r\n");
      out.write("  \r\n");
      out.write("   <h5 style=\"text-decoration: underline;\">Personal Information</h5>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("              <label id=\"fname\">  First Name: </label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("              <label id=\"lname\">  Last Name:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("             <label id=\"gender\"> Gender:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("             <label id=\"gender\">  Age:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("             <label id=\"email\">   Email ID:</label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("             <label id=\"bid\">     Body Map ID: </label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.BID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("  </div> \r\n");
      out.write("    \r\n");
      out.write("    <!--1st row second column  -->\r\n");
      out.write("\r\n");
      out.write("    </div><!--Row -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   <div class=\"row\"> \r\n");
      out.write("   <div class=\"col-lg-6\" style=\"width: 100%\">\r\n");
      out.write("      <h5 style=\"text-decoration: underline;\">Disease Information</h5>           \r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("              <table class=\"table table-hover tablesorter\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                  <th>BID</th>\r\n");
      out.write("                    <th>Disease Code </th>\r\n");
      out.write("                    <th>Disease Name </th>\r\n");
      out.write("                    <th>Date of Diagnosis </th>\r\n");
      out.write("                    <th>Disease Description </th>\r\n");
      out.write("               \r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <form name=\"disease\" id=\"disease\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div><!--Disease Table Row  -->\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div id=\"obj\" style=\"left: 12%; position: relative;\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \t<svg style=\"width: 100%; height: 100%; position: absolute; top:0; left:0;\">\r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </svg>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write("   </form>\r\n");
      out.write("   <a href=\"#\" id=\"switch\" style=\"top: 40% ; left:86.75%; position: absolute;\"> <i class=\"fa fa-chevron-right\" id=\"switch\"></i></a>\r\n");
      out.write("  </div><!--Close Column1  -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   </div><!--Row Close1  -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <!--  <div id=\"obj\" style=\"top:30px;position: absolute;border:1px solid;border-radius:25px;\"></div> -->\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write(" </div><!--Page Wrapper  -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.container -->\r\n");
      out.write("    \r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterLayout.jsp", out, false);
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /DoctorPrintReport.jsp(233,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /DoctorPrintReport.jsp(235,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /DoctorPrintReport.jsp(235,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(annotation)-1}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).intValue());
    // /DoctorPrintReport.jsp(235,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("index");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write(" <tr>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getBID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getDiseaseCode()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getExtraDiseaseName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\t\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getDateOfDiag()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getDiseaseDesc()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\r\n");
          out.write("                   \r\n");
          out.write(" \t\t\t\t\r\n");
          out.write(" </tr>\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /DoctorPrintReport.jsp(263,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /DoctorPrintReport.jsp(265,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(0);
    // /DoctorPrintReport.jsp(265,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(annotation)-1}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).intValue());
    // /DoctorPrintReport.jsp(265,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("index");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("              \r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\t <a href=\"About.jsp\" id=\"annotationsLink\" data-ot=\"Disease Code:");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getDiseaseCode()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" data-ot-hide-trigger=\"trigger\" data-ot-target=\"true\"> <circle cx=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getX_Coord()+2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" cy=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getY_Coord()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" r=\"6\" fill=\"yellow\" />\r\n");
          out.write("\t\t\t\t\t<text dx=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getX_Coord()+12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" dy=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getY_Coord()+4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${annotation[index].getExtraDiseaseName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</text></a> \r\n");
          out.write("\t\t\t\t\t \r\n");
          out.write("\t\t\t\t\t \r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
