/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-11-20 09:05:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HeaderLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("   <meta http-equiv=\"refresh\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.session.maxInactiveInterval}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("; url=Error.jsp\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("\r\n");
      out.write("  \t<link rel=\"icon\" type=\"image/png\" href=\"img/icon.PNG\">\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("     <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("     <script src=\"js/jquery.js\"></script>\r\n");
      out.write("     <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("     <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $( document ).ready(function() {\r\n");
      out.write("    \t\r\n");
      out.write("    \t\t\r\n");
      out.write("        /* \tdocument.location.href=\"userDetailsForDoctor\"; */\r\n");
      out.write("        \r\n");
      out.write("    \t var session = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("    \t \r\n");
      out.write("    \t if(session)\r\n");
      out.write("    \t\t {\r\n");
      out.write("    \t\t  $('#loginlogout').text('Logout'); \r\n");
      out.write("    \t\t\t  $('#loginlogout').attr(\"href\",\"Logout.jsp\");\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \r\n");
      out.write("    \t\t }\r\n");
      out.write("    \t else\r\n");
      out.write("    \t\t {\r\n");
      out.write("    \t\t document.getElementById('mymenutop').style.visibility='hidden'; \r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t }\r\n");
      out.write("  \r\n");
      out.write("    \t if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.role}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'==\"Patient\")\r\n");
      out.write("    \t\t {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t $(\"#dash\").remove();\r\n");
      out.write("    \t\t $(\"#edit\").remove();\r\n");
      out.write("    \t\t $('#view').attr(\"href\",\"PatientLandingPage.jsp\");\r\n");
      out.write("    \t\t $('#report').attr(\"href\",\"PatientPrintReport.jsp\");    \t\t \r\n");
      out.write("    \t\t }\r\n");
      out.write("   \t});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"heading\">2D Body Map for EHR</div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-default\" role=\"navigation\" style=\"position: relative;\">\r\n");
      out.write("      <div class=\"container\" >\r\n");
      out.write("        <div class=\"navbar-header\" >\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"Home.jsp\">2D Body Map for EHR</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("        <div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li><a href=\"Home.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href=\"About.jsp\">About 2DBM</a></li>\r\n");
      out.write("            <li><a href=\"Register.jsp\">Patient Registration</a></li>\r\n");
      out.write("                 <li><a id=\"loginlogout\" href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                 \r\n");
      out.write("          </ul>\r\n");
      out.write("        \r\n");
      out.write("        </div><!-- /.navbar-collapse -->\r\n");
      out.write("      </div><!-- /.container -->\r\n");
      out.write("         </nav>\r\n");
      out.write("       <div id=\"mymenutop\" class=\"btn-group\" style=\" position:relative; margin-top: -250px; left:81%; z-index:100000;\">\r\n");
      out.write("\t   <button type=\"button\" class=\"btn btn-default\" style=\"width: auto;\"><i class=\"fa fa-user\"></i>&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</button>\r\n");
      out.write("       <button type=\"button\" id=\"dropdownid\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" style=\"padding-left: 14px\"><span class=\"caret\"></span></button>\r\n");
      out.write("         <ul class=\"dropdown-menu\" style=\"width: 90%\">\r\n");
      out.write("                   <li id=\"dash\" style=\"height: 30px;\"><a  href=\"DoctorLandingPage.jsp\"><i class=\"fa fa-dashboard\"></i>&nbsp;&nbsp;DashBoard</a></li>\r\n");
      out.write("                   <li style=\"height: 30px;\"><a href=\"DoctorViewMode.jsp\" id=\"view\"><i class=\"fa fa-eye\"></i>&nbsp;&nbsp;View Mode</a></li>\r\n");
      out.write("                   <li id=\"edit\" style=\"height: 30px;\"><a  href=\"DoctorEditMode.jsp\"><i class=\"fa fa-edit\"></i>&nbsp;&nbsp;Edit Mode</a></li>        \r\n");
      out.write("                   <li style=\"height: 30px;\"><a href=\"DoctorPrintReport.jsp\" id=\"report\"><i class=\"fa fa-print\"></i>&nbsp;&nbsp;Print Report</a></li>   \r\n");
      out.write("                   <li class=\"divider\"></li>   \r\n");
      out.write("                   <li style=\"height: 30px;\"><a href=\"Logout.jsp\" id=\"logout\"><i class=\"fa fa-sign-out\"></i>&nbsp;&nbsp;Logout</a></li>                   \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
