/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-11-20 09:07:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("  \t<link rel=\"icon\" type=\"image/png\" href=\"img/icon.PNG\">\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("     \r\n");
      out.write("     <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("     <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){       \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t// function to make AJAX call to the server\r\n");
      out.write("\t$(\"#login\").submit(function(e){\r\n");
      out.write("\t  console.log(\"in submit\");\r\n");
      out.write("\t     e.preventDefault();\r\n");
      out.write("\t     var formdata = new Object();\r\n");
      out.write("\t     var inpele = document.getElementsByTagName(\"input\");\r\n");
      out.write("\t     for (var i = 0; i < inpele.length; i++) {\r\n");
      out.write("\t       formdata[inpele[i].name] = inpele[i].value;\r\n");
      out.write("\t      }\r\n");
      out.write("\t     frmd = JSON.stringify(formdata);\r\n");
      out.write("\t    \r\n");
      out.write("\t   $.ajax ({\r\n");
      out.write("\t        \t\t\turl : \"SignInAction\",\r\n");
      out.write("\t        \t\t\ttype : \"POST\",\r\n");
      out.write("\t        \t\t\tdataType: \"json\",\r\n");
      out.write("\t                    async: false,\r\n");
      out.write("\t        \t\t\tdata : frmd,      \t\t\t\r\n");
      out.write("\t \t\t\t\t    success: function(data) {\t \r\n");
      out.write("\t \t\t\t\t    \t\r\n");
      out.write("\t \t\t\t\t    \t\r\n");
      out.write("\t \t\t\t\t    \t var session = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t \t\t\t\t    \t \r\n");
      out.write("\t \t\t\t\t    \tif(data)\r\n");
      out.write("\t \t\t\t\t    \t\t{\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t if(data.role==\"Doctor\")\r\n");
      out.write("\t\t\t \t\t\t\t    \t{\r\n");
      out.write("\t\t \t\t\t\t    \t\t    \t\t\r\n");
      out.write("\t\t\t \t\t\t\t    \t\tlocation.href = 'DoctorLandingPage.jsp?session='+ session;\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t\r\n");
      out.write("\t\t\t \t\t\t\t    \t}\r\n");
      out.write("\t\t\t \t\t\t\t    \telse if(data.role==\"Patient\")\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t{\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t\r\n");
      out.write("\t\t\t \t\t\t\t    \t\tlocation.href = 'PatientLandingPage.jsp?session='+ session;;\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t\r\n");
      out.write("\t\t\t \t\t\t\t    \t\t}\t \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t}\r\n");
      out.write("\t \t\t\t\t    \telse\r\n");
      out.write("\t \t\t\t\t    \t\t{\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\tdocument.getElementById('errorDiv').style.visibility='visible'; \r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t}\r\n");
      out.write("\t \t\t\t\t    \t\t\r\n");
      out.write("\t \t\t\t\t    \t\t\t\t    \t\r\n");
      out.write("\t \t\t\t\t\t    \t\r\n");
      out.write("\t \t\t\t\t    \t\r\n");
      out.write("\t \t\t\t\t    \t\r\n");
      out.write("\t \t\t/* \t\t    \talert(data); */\r\n");
      out.write("\t        \t\t            \r\n");
      out.write("\t        \t\t         /*  alert(data.firstName); */\r\n");
      out.write("\t        \t\t          \r\n");
      out.write("\t        \t\t          \r\n");
      out.write("\t      \r\n");
      out.write("\t        \t\t         \r\n");
      out.write("\t        \t\t },\r\n");
      out.write("\t        \t\t        error: function() {\r\n");
      out.write("\t        \t\t        \t\r\n");
      out.write("\t        \t\t        \tdocument.getElementById('errorDiv').style.visibility='visible'; \r\n");
      out.write("\t        \t\t            /* alert(\"An error occured while attempting fetch data.\"); */\r\n");
      out.write("\t        \t\t            \r\n");
      out.write("\t        \t\t            \r\n");
      out.write("\t        \t\t        }\r\n");
      out.write("\t        \t\t\t\r\n");
      out.write("\t      \t\t });\r\n");
      out.write("\t     \r\n");
      out.write("   \t\r\n");
      out.write("\t });   \r\n");
      out.write("\t\r\n");
      out.write("/* \t  var patientGender = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t alert(patientGender);  */\r\n");
      out.write("\t\r\n");
      out.write(" }); \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderLayout.jsp", out, false);
      out.write("\r\n");
      out.write("       <div class=\"container\" style=\"height: 100%\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\" style=\"height: 710px\">\r\n");
      out.write("        <div class=\"box\" style=\"height: 100%\">\r\n");
      out.write("          <div class=\"row\" style=\"border:1px solid; position: absolute;border-radius:25px;width: 30%; top:40%;  left: 36%;\"   > \r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h2 class=\"intro-text text-center\">Login <strong>form</strong></h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("          \r\n");
      out.write("                 <form role=\"form\" id = \"login\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                  \r\n");
      out.write("                    <div class=\"form-group col-lg-11\" style=\"left: 2%;\">\r\n");
      out.write("                      <label>Enter your Email: <span class=\"required\">*</span></label>\r\n");
      out.write("                      <input id = \"email\" type = \"email\" class=\"form-control\" name = \"email\" placeholder = \"John@gmail.com\" required/>                     \r\n");
      out.write("                    </div>\r\n");
      out.write(" \t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("                    <div class=\"form-group col-lg-11\" style=\"left: 2%;\">\r\n");
      out.write("                      <label>Enter your Password: <span class=\"required\">*</span> </label>\r\n");
      out.write("                      <input id = \"pwd\" class=\"form-control\" type = \"password\" name = \"pwd\" required=\"required\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                  <!--   <div class=\"clearfix\"></div>\r\n");
      out.write("                      <div class=\"form-group col-lg-12\" style=\"left: 24px;\">                   \r\n");
      out.write("                 \t  <input type=\"checkbox\" name=\"loginkeeping\" id=\"loginkeeping\" value=\"loginkeeping\" /> \r\n");
      out.write("\t\t\t\t\t  <label for=\"loginkeeping\">Keep me logged in</label>\t\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                  \r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                      <div class=\"form-group col-lg-11\" style=\"left: 2%;\">                   \r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary\" style=\"width:100%\">Login</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"alert alert-danger alert-dismissable\" id=\"errorDiv\" style=\"visibility: hidden;\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"alert\" id=\"error\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("              Invalid User Name or Password!! Please Enter Valid Credentials or Register!\r\n");
      out.write("            </div>\r\n");
      out.write("             <p class=\"change_link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNot a member yet ?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Register.jsp\" class=\"to_register\">Join us</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("              </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div><!-- /.container -->\r\n");
      out.write("    \r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterLayout.jsp", out, false);
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
